### ISSUE TITLE
Can't start server - Error: connect ECONNREFUSED 127.0.0.1:8546

### ISSUE THREAD

**Issue by alexbarnsley** [thusfresh/onyx-server#17]
Installed server globally but can't seem to start it. List of commands are below:

```
$ npm install --global onyx-server
$ DEBUG="onyx*" onyx-server --port 5000 --http-url http://localhost:8500 --ws-url ws://localhost:8546
  onyx:pss:client connecting to Swarm ws://localhost:8546 +0ms
(node:26518) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:8546
(node:26518) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

```
$ node -v
v8.9.1
$ npm -v
5.5.1
```

Let me know if you need more information. Thanks!

**Comment by PaulLeCam** [comment]
It seems like your Swarm node is not running, is it properly setup?
If you haven't installed Swarm yet, you could try using https://github.com/MainframeHQ/onyx-toolbox that provides a CLI to do the setup.

**Comment by alexbarnsley** [comment]
Ah i didn't realise Swarm was needed too for the onyx-server. Possibly worth a mention on the README 😄  I'm just in the process of doing onyx-toolbox now (installing Go, etc). Next error I've got is:

```
$ onyx start
 ❯ Start Swarm
   ❯ Setup Swarm environment
     ✔ Check environment dependencies
     ✔ Check working directory
     ✔ Clone MainframeHQ/go-ethereum
     ✔ Fetch latest update
     ✖ Build geth
       → >>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=568f99f2e173f7c3ffae575ea74a07fa0741121f -v ./cmd/geth
       Build swarm
       Check data directory
       Create password file
       Create account
       Save configuration
     Start Swarm
   Start the Onyx server
Error: Command failed: build/env.sh go run build/ci.go install ./cmd/geth
util.go:44: fork/exec /usr/local/go/bin/go: no such file or directory
exit status 1

>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=568f99f2e173f7c3ffae575ea74a07fa0741121f -v ./cmd/geth

    at Promise.all.then.arr (/home/alex/.nvm/versions/node/v8.9.1/lib/node_modules/onyx-toolbox/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by PaulLeCam** [comment]
The issue seems to be the script is trying to run `/usr/local/go/bin/go` but cannot find it, is Go properly setup in your system?
You may have a better luck using this script if the toolbox doesn't support your setup: https://github.com/MainframeHQ/onyx-server/blob/master/start_swarm_node.sh

**Comment by PaulLeCam** [comment]
@alexbarnsley Sorry I missed the fact we added the script to this repository as well, should be similar to the one in our `onyx-packer` repository: https://github.com/MainframeHQ/onyx-server/blob/master/start_swarm_node.sh

**Comment by alexbarnsley** [comment]
Ah yes, thanks @PaulLeCam! I installed Go correctly so that's now all working, and I can start the server using onyx-toolbox. How can I go about making that run on a public address? I tried setting SWARM_WS_URL to the public IP but it then fails to connect, I guess because swarm is looking on localhost only. Is that correct?

**Comment by PaulLeCam** [comment]
Yes the toolbox is mostly meant for local development, it might not be a proper setup for server deployment, sorry.

Assuming Swarm and Onyx server are running on the same machine, it should be OK to connect the `SWARM_WS_URL` on localhost, it's the Onyx server that need to be open to the public.
By default it listens on port 5000 but you can change it using the `--port` flag when starting `onyx-server` from the CLI.

**Comment by alexbarnsley** [comment]
Ah okay, that makes sense. I was going to try and do a public server for everyone to connect to instead of running locally. I'll take another look in a few days when i've got a bit more free time! You can close this if you like, as it may not strictly be an issue with the server/toolbox 😄

**Comment by PaulLeCam** [comment]
OK I'll close it for now, but don't hesitate to ping us if you have any other issue!
